export * from './data.ts'
export { default as Clients } from './Clients.tsx'
export { default as FAQs } from './FAQs.tsx'
export { default as Features } from './Features.tsx'
export { default as Footer } from './Footer.tsx'
export { default as PricingCards } from './PricingCards.tsx'
export { default as FeedBack } from './FeedBack.tsx'
export { default as Testimonial } from './Testimonial.tsx'
export { default as Footer2 } from './Footer2.tsx'
export { default as Footer3 } from './Footer3.tsx'
export { default as Footer4 } from './Footer4.tsx'
export { default as Navbar } from './Navbar.tsx'
export { default as PricingCards2 } from './PricingCards2.tsx'
